[package]
name = "eth-riscv-interpreter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rvemu = { git = "https://github.com/lvella/rvemu.git" }
goblin = "0.8.2"
