[workspace]

resolver = "2"

members = [ "eth-riscv-interpreter",
    "eth-riscv-syscalls",
]

exclude = [ "erc20", "eth-riscv-runtime" ]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/leonardoalt/r5"

[workspace.dependencies]
