[package]
name = "r55"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
revm = { path = "../../revm-rv/crates/revm" }

[[bin]]
name = "r55"
