[package]
name = "r55"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
revm = { git = "https://github.com/r0qs/revm" }

[[bin]]
name = "r55"
